logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

# WEB interface of Traefik - it will show web page with overview of frontend and backend configurations
#[web]
#address = ":8080"

# Connection to docker host system (docker.sock)
#[docker]
#swarmmode = true
#domain = "dockers.mach5.web.id"
#watch = true
# This will hide all docker containers that don't have explicitly
# set label to "enable"
#exposedbydefault = false


[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/certs/cert.pem"
      keyFile = "/certs/privkey.pem"
